const constants = {
  ALPHABET: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  ROTOR_PERMUTATIONS: [
    'BDFHJLCPRTXVZNYEIWGAKMUSQO',
    'AJDKSIRUXBLHWTMCQGZNPYFVOE',
    'EKMFLGDQVZNTOWYHXUSPAIBRCJ',
  ],
  REFLECTOR_PERMUTATION: 'IXUHFEZDAOMTKQJWNSRLCYPBVG',
};
